# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f3ab5f0e9bcd156c545d566272f3100d3a7ed0129b5c065ce8562f7b7249edb91011dd2cc542554f5c4d21624833fa69dd52837c19eb68ad280f81a332f404a

test:
  secret_key_base: e9106dead6ac938f61b01d26bdb75af4ef71f512217ba2e1fef72f1c2c9b64478bdc6575d78eefba9e67fff039d5589ea219697e6353dc7d4d375f5714c5779e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
